//! Curve markers keep the base/scalar pairing out of field APIs.

use crate::field::{PallasBase, PallasScalar, PrimeModulus};

mod sealed {
    pub trait Sealed {}
}

/// Selects Pallas or Vesta and its base and scalar moduli.
///
/// The base field contains coordinates satisfying `y² = x³ + 5`. The scalar
/// modulus is the curve's prime group order, so every point on the curve is in
/// the subgroup generated by `(-1, 2)`.
///
/// This trait is sealed; only [`Pallas`] and [`Vesta`] implement it.
pub trait PastaCurve: sealed::Sealed + Copy + Eq + Send + Sync + 'static {
    /// Modulus marker for the field containing point coordinates.
    type Base: PrimeModulus;
    /// Modulus marker for the field of scalars acting on this curve.
    type Scalar: PrimeModulus;
}

/// Pallas, with coordinates in [`crate::field::Fp`] and scalars in
/// [`crate::field::Fq`].
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum Pallas {}

/// Vesta, with coordinates in [`crate::field::Fq`] and scalars in
/// [`crate::field::Fp`].
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum Vesta {}

impl sealed::Sealed for Pallas {}
impl sealed::Sealed for Vesta {}

impl PastaCurve for Pallas {
    type Base = PallasBase;
    type Scalar = PallasScalar;
}

impl PastaCurve for Vesta {
    type Base = PallasScalar;
    type Scalar = PallasBase;
}
