//! Table-assisted square roots in the Pasta fields.
//!
//! Write the field modulus as `p = t * 2^32 + 1`, with odd `t`, and let
//! `r = 5^t`, a root of order `2^32`. For nonzero input `a`, the shared
//! exponentiation supplies `w = a^((t - 1) / 2)`. Then `x3 = a * w^2 = a^t`
//! lies in the subgroup generated by `r`, and `(a * w)^2 = a * x3`.
//!
//! Recover `e` in `0..2^32` such that `x3 * r^e = 1`. Raising to powers of
//! 256 isolates its four base-256 digits. An inverse-exponent lookup in the
//! order-256 subgroup recovers each digit; power tables cancel the digits
//! already recovered before the next lookup.
//!
//! For even `e`, the square root is `a * w * r^(e / 2)`. An odd `e` means
//! `a` is a nonsquare: rounding the exponent up gives a candidate whose square
//! is `a * r`. The final square check distinguishes these cases.

use super::{PastaField, PrimeModulus, Reduced, field_elements};

/// Powers of `r` and inverse exponents for its order-256 subgroup.
///
/// Each `gi[j]` stores `r^(j * 256^i)` in reduced Montgomery form. The inverse
/// table maps all 256 powers `r^(j * 256^3)` to `-j mod 256` through [`hash`].
pub(crate) struct LargeSqrtTable<F> {
    g0: [F; 256],
    g1: [F; 256],
    g2: [F; 256],
    // Only the final correction uses g3. Rounding e/2 reaches at most 2^31,
    // so the top byte indexes at most entry 128.
    g3: [F; 129],
    inverse: [u8; 1024],
}

// Hash the low 32 bits of a reduced Montgomery residue into ten bits.
// from_powers checks injectivity on the order-256 subgroup for each field.
const fn hash(key: u32, multiplier: u32) -> usize {
    (key.wrapping_mul(multiplier) >> 22) as usize
}

// Widen before rounding: the inverse exponent can be u32::MAX, as for input five.
const fn half_exponent(exponent: u32) -> u32 {
    ((exponent as u64 + 1) >> 1) as u32
}

impl<M: PrimeModulus> LargeSqrtTable<PastaField<M, Reduced>> {
    /// Builds power and inverse-exponent tables from Montgomery limbs.
    ///
    /// Requires `powers[i][j]` to represent `r^(j * 256^i)` for `i` in `0..4`
    /// and `j` in `0..256`, where `r` has order `2^32`. The caller establishes
    /// this power progression. Construction checks that all entries are reduced
    /// and that `multiplier` gives distinct hashes for all 256 entries of the
    /// fourth table, before retaining only the entries needed for correction.
    ///
    /// # Panics
    ///
    /// Panics if an entry is unreduced or two subgroup elements hash alike.
    pub(in crate::field) const fn from_powers(
        powers: [[[u64; 4]; 256]; 4],
        multiplier: u32,
    ) -> Self {
        let full_g3 = field_elements::<M, 256>(powers[3]);
        let mut g3 = [PastaField::ZERO; 129];
        let mut inverse = [0; 1024];
        let mut occupied = [false; 1024];
        let mut j = 0;
        while j < 256 {
            let slot = hash(full_g3[j].montgomery_limbs()[0] as u32, multiplier);
            assert!(!occupied[slot], "square-root subgroup hash collision");
            occupied[slot] = true;
            inverse[slot] = (j as u8).wrapping_neg();
            if j < g3.len() {
                g3[j] = full_g3[j];
            }
            j += 1;
        }
        Self {
            g0: field_elements(powers[0]),
            g1: field_elements(powers[1]),
            g2: field_elements(powers[2]),
            g3,
            inverse,
        }
    }

    /// Computes a square root using the prepared power and correction tables.
    ///
    /// Requires nonzero `value`, `w = value^((t - 1) / 2)`, and the same
    /// `multiplier` used by [`Self::from_powers`]. Here `p - 1 = t * 2^32`,
    /// where `p` is the field modulus. Returns `None` for a nonsquare.
    pub(in crate::field) fn sqrt(
        &self,
        value: &PastaField<M, Reduced>,
        w: PastaField<M>,
        multiplier: u32,
    ) -> Option<PastaField<M, Reduced>> {
        let x = value.mul(&w);
        let (_, candidate) = self.finish(x, x.mul(&w), multiplier);
        (candidate.square().reduce() == *value).then(|| candidate.reduce())
    }

    /// Corrects `x` with `x^2 = a * t` for nonzero `a` and order-2^32
    /// subgroup element `t`, using the construction's hash multiplier.
    /// An odd inverse exponent returns a root of `a * r` and a false flag.
    pub(in crate::field) fn finish(
        &self,
        x: PastaField<M>,
        t: PastaField<M>,
        multiplier: u32,
    ) -> (bool, PastaField<M>) {
        let inverse = |x: PastaField<M>| {
            self.inverse[hash(x.reduce().montgomery_limbs()[0] as u32, multiplier)] as u32
        };
        // Squaring stays loose; only the hash key needs a unique representative.
        let square_eight = |x: PastaField<M>| {
            PastaField::from_montgomery(crate::field::montgomery::square_run::<M>(
                &x.montgomery_limbs(),
                8,
                None,
            ))
        };
        let x3 = t;
        let x2 = square_eight(x3);
        let x1 = square_eight(x2);
        let x0 = square_eight(x1);

        // Recover e such that x3 * r^e = 1, one byte at a time.
        // Each correction puts the next hash input in the order-256 subgroup.
        let mut e = inverse(x0);
        let alpha = x1.mul(&self.g2[e as usize]);
        e |= inverse(alpha) << 8;
        let alpha = x2
            .mul(&self.g1[(e & 255) as usize])
            .mul(&self.g2[(e >> 8) as usize]);
        e |= inverse(alpha) << 16;
        let alpha = x3
            .mul(&self.g0[(e & 255) as usize])
            .mul(&self.g1[((e >> 8) & 255) as usize])
            .mul(&self.g2[(e >> 16) as usize]);
        e |= inverse(alpha) << 24;

        let is_square = e & 1 == 0;
        let e = half_exponent(e);
        let candidate = x
            .mul(&self.g0[(e & 255) as usize])
            .mul(&self.g1[((e >> 8) & 255) as usize])
            .mul(&self.g2[((e >> 16) & 255) as usize])
            .mul(&self.g3[(e >> 24) as usize]);
        (is_square, candidate)
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::field::{PallasBase, PallasScalar};
    use num_bigint::BigUint;

    fn check<M: PrimeModulus>(table: &LargeSqrtTable<PastaField<M, Reduced>>, multiplier: u32) {
        assert_eq!(size_of_val(table), 897 * 32 + 1024);
        let modulus = BigUint::from_bytes_le(&M::MODULUS.map(u64::to_le_bytes).concat());
        let root = BigUint::from(5u8).modpow(&((&modulus - 1u8) >> 32usize), &modulus);
        // Check the actual stored entries with independent integer powers.
        for (digit, entries) in [table.g0.as_slice(), &table.g1, &table.g2, &table.g3]
            .into_iter()
            .enumerate()
        {
            for (j, value) in entries.iter().enumerate() {
                let expected = root.modpow(&(BigUint::from(j) << (digit * 8)), &modulus);
                assert_eq!(BigUint::from_bytes_le(&value.to_bytes()), expected);
            }
        }
        let step = PastaField::<M>::root_of_unity(8).unwrap();
        let mut value = PastaField::ONE;
        let mut occupied = [false; 1024];
        for j in 0..256 {
            let slot = hash(value.reduce().montgomery_limbs()[0] as u32, multiplier);
            assert!(!occupied[slot]);
            occupied[slot] = true;
            assert_eq!(table.inverse[slot], (j as u8).wrapping_neg());
            assert_eq!(
                (value.mul(&step.pow_u64(table.inverse[slot] as u64))).reduce(),
                (PastaField::<_>::ONE).reduce()
            );
            value = value.mul(&step);
        }
        assert_eq!((value).reduce(), (PastaField::<_>::ONE).reduce());
    }

    #[test]
    fn powers_and_hashes_match_independent_references() {
        check::<PallasBase>(PallasBase::SQRT_TABLE, 0x54c1_1db5);
        check::<PallasScalar>(PallasScalar::SQRT_TABLE, 0x4b7f_dd31);
    }

    // Rebuild the constructor's required power progression at runtime.
    fn runtime_powers<M: PrimeModulus>() -> [[[u64; 4]; 256]; 4] {
        let root = PastaField::<M>::root_of_unity(32).unwrap();
        let mut powers = [[[0; 4]; 256]; 4];
        for (digit, entries) in powers.iter_mut().enumerate() {
            for (j, entry) in entries.iter_mut().enumerate() {
                *entry = root
                    .pow_u64((j as u64) << (8 * digit))
                    .reduce()
                    .montgomery_limbs();
            }
        }
        powers
    }

    fn check_construction<M: PrimeModulus>(
        shipped: &LargeSqrtTable<PastaField<M, Reduced>>,
        multiplier: u32,
    ) {
        // Valid inputs must reproduce the shipped table exactly, so the
        // rejections below cannot hide an unrelated input problem.
        let powers = runtime_powers::<M>();
        let table = LargeSqrtTable::<PastaField<M, Reduced>>::from_powers(powers, multiplier);
        assert_eq!(table.g0, shipped.g0);
        assert_eq!(table.g1, shipped.g1);
        assert_eq!(table.g2, shipped.g2);
        assert_eq!(table.g3, shipped.g3);
        assert_eq!(table.inverse, shipped.inverse);

        // Multiplier zero hashes every subgroup element to one slot.
        assert!(
            std::panic::catch_unwind(|| LargeSqrtTable::<PastaField<M, Reduced>>::from_powers(
                powers, 0
            ))
            .is_err()
        );
        // An unreduced entry in any digit table is rejected, including in the
        // tables that construction checks after the hash loop.
        for digit in 0..4 {
            let mut unreduced = powers;
            unreduced[digit][7] = M::MODULUS;
            assert!(
                std::panic::catch_unwind(|| LargeSqrtTable::<PastaField<M, Reduced>>::from_powers(
                    unreduced, multiplier
                ))
                .is_err()
            );
        }
    }

    #[test]
    fn construction_rejects_hash_collisions_and_unreduced_entries() {
        check_construction::<PallasBase>(PallasBase::SQRT_TABLE, 0x54c1_1db5);
        check_construction::<PallasScalar>(PallasScalar::SQRT_TABLE, 0x4b7f_dd31);
    }

    #[test]
    fn half_exponent_rounds_up_without_word_overflow() {
        for (e, half) in [
            (0, 0),
            (1, 1),
            (2, 1),
            (u32::MAX - 1, 0x7fff_ffff),
            (u32::MAX, 0x8000_0000),
        ] {
            assert_eq!(half_exponent(e), half);
        }
    }
}
