[package]
name = "zakura-bento-core"
description = """
Implementation crate behind the bento facade; depend on `bento` instead
"""
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dev-dependencies]
num-bigint = "0.4"
