//! Curve markers keep the base/scalar pairing out of field APIs.

use crate::field::{PallasBase, PallasScalar, PrimeModulus};

mod sealed {
    pub trait Sealed {}

    /// Positive coordinates defining the kernel columns documented on `GlvBasis`.
    pub(crate) trait Parameters {
        /// First coordinate of the first kernel column.
        const GLV_A: u128;
        /// Negated second coordinate of the first kernel column.
        const GLV_B: u128;
    }
}

/// Selects Pallas or Vesta and its base and scalar moduli.
///
/// The base field contains coordinates satisfying `y² = x³ + 5`. The scalar
/// modulus is the curve's prime group order, so every point on the curve is in
/// the subgroup generated by `(-1, 2)`.
///
/// This trait is sealed; only [`Pallas`] and [`Vesta`] implement it.
#[expect(private_bounds, reason = "implementation parameters are crate-private")]
pub trait PastaCurve:
    sealed::Sealed + sealed::Parameters + Copy + Eq + Send + Sync + 'static
{
    /// Modulus marker for the field containing point coordinates.
    type Base: PrimeModulus;
    /// Modulus marker for the field of scalars acting on this curve.
    type Scalar: PrimeModulus;
}

/// Pallas, with coordinates in [`crate::field::Fp`] and scalars in
/// [`crate::field::Fq`].
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum Pallas {}

/// Vesta, with coordinates in [`crate::field::Fq`] and scalars in
/// [`crate::field::Fp`].
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum Vesta {}

impl sealed::Sealed for Pallas {}
impl sealed::Sealed for Vesta {}

impl sealed::Parameters for Pallas {
    const GLV_A: u128 = 0x49e69d1640f049157fcae1c700000001;
    const GLV_B: u128 = 0x49e69d1640a899538cb1279300000000;
}
impl sealed::Parameters for Vesta {
    const GLV_A: u128 = 0x49e69d1640f049157fcae1c700000000;
    const GLV_B: u128 = 0x49e69d1640a899538cb1279300000001;
}

impl PastaCurve for Pallas {
    type Base = PallasBase;
    type Scalar = PallasScalar;
}

impl PastaCurve for Vesta {
    type Base = PallasScalar;
    type Scalar = PallasBase;
}

/// A basis for scalar pairs representing zero modulo the group order.
///
/// Let `n` be the scalar modulus, `lambda` the scalar field's cube root of
/// unity, and `d = a + b`. Columns `(a, -b)` and `(b, d)` lie in the kernel of
/// `(x, y) -> x + lambda*y mod n`. Their determinant is `n`, so they generate
/// the full kernel lattice. The fixed-point coefficients are
/// `g1 = round(2^384 * d/n)` and `g2 = round(2^384 * b/n)`.
pub(super) struct GlvBasis {
    pub(super) a: u128,
    pub(super) b: u128,
    pub(super) d: u128,
    pub(super) g1: [u64; 5],
    pub(super) g2: [u64; 5],
}

pub(crate) struct GlvParameters<C>(core::marker::PhantomData<C>);

impl<C: PastaCurve> GlvParameters<C> {
    const A: [u64; 4] = [C::GLV_A as u64, (C::GLV_A >> 64) as u64, 0, 0];
    const B: [u64; 4] = [C::GLV_B as u64, (C::GLV_B >> 64) as u64, 0, 0];
    const D: u128 = C::GLV_A + C::GLV_B;
    const D_LIMBS: [u64; 4] = [Self::D as u64, (Self::D >> 64) as u64, 0, 0];
    const AD: [u64; 8] = bento::const_arithmetic::u256::mul_wide!(&Self::A, &Self::D_LIMBS);
    const BB: [u64; 8] = bento::const_arithmetic::u256::mul_wide!(&Self::B, &Self::B);

    /// Conservative Babai residual magnitudes, including rounding error.
    pub(crate) const BOUNDS: [u128; 2] =
        [(C::GLV_A + C::GLV_B) / 2 + 1, (C::GLV_B + Self::D) / 2 + 1];

    /// Number of width-eight data windows, requiring no extra carry window.
    pub(crate) const BOOTH_WINDOWS: usize = {
        // The top byte plus an incoming carry stays below the positive centered
        // digit threshold. Negating a component therefore needs no extra row either.
        assert!((Self::BOUNDS[0] >> 120) + 1 < 128);
        assert!((Self::BOUNDS[1] >> 120) + 1 < 128);
        16
    };

    pub(super) const BASIS: GlvBasis = {
        use bento::const_arithmetic::{m255, u256};
        let (determinant, carry) = u256::add_with_carry!(
            &[Self::AD[0], Self::AD[1], Self::AD[2], Self::AD[3]],
            &[Self::BB[0], Self::BB[1], Self::BB[2], Self::BB[3]],
        );
        assert!(carry == 0);
        let a = m255::from_u256!(&C::Scalar::MODULUS, &Self::A);
        let lambda_b = m255::mul!(
            &C::Scalar::MODULUS,
            &crate::field::PastaField::<C::Scalar>::ZETA.montgomery_limbs(),
            &m255::from_u256!(&C::Scalar::MODULUS, &Self::B),
        );
        let second = m255::add!(
            &C::Scalar::MODULUS,
            &m255::from_u256!(&C::Scalar::MODULUS, &Self::B),
            &m255::mul!(
                &C::Scalar::MODULUS,
                &crate::field::PastaField::<C::Scalar>::ZETA.montgomery_limbs(),
                &m255::from_u256!(&C::Scalar::MODULUS, &Self::D_LIMBS),
            ),
        );
        let mut i = 0;
        while i < 4 {
            assert!(Self::AD[i + 4] == 0 && Self::BB[i + 4] == 0);
            assert!(determinant[i] == C::Scalar::MODULUS[i]);
            assert!(a[i] == lambda_b[i] && second[i] == 0);
            i += 1;
        }
        // Here n is the scalar modulus. Rounding g1 and g2 introduces at most
        // n/2^385 error in the inverse-basis coefficients for a scalar k < n.
        // Rounding those coefficients adds at most 1/2 to that error.
        // Since n < 2^255 and both coordinate sums are < 2^128, each
        // residual magnitude is less than half its coordinate sum plus one.
        assert!(C::Scalar::MODULUS[3] < 1 << 63);
        assert!((C::GLV_A + C::GLV_B) / 2 + 1 < 1 << 127);
        assert!((C::GLV_B + Self::D) / 2 + 1 < 1 << 127);
        GlvBasis {
            a: C::GLV_A,
            b: C::GLV_B,
            d: Self::D,
            g1: u256::round_shifted_ratio!(&C::Scalar::MODULUS, Self::D, 384),
            g2: u256::round_shifted_ratio!(&C::Scalar::MODULUS, C::GLV_B, 384),
        }
    };
}
