[package]
name = "zakura-udon"
description = "Optimized Pasta field and curve arithmetic"
version = "0.1.0"
authors = ["Sean Bowe <ewillbefull@gmail.com>"]
edition = "2024"
rust-version = "1.91"
license = "MIT OR Apache-2.0"
publish = false

[dependencies]
bento = { package = "zakura-bento", path = "../bento" }
